#ifndef CONFIG_INCLUDED
#define CONFIG_INCLUDED

#define CEIL(a, b) (((a) + (b) - 1) / (b))

#define NODE_LIMIT 32
#define FUTURE_LIMIT 32
#define HEARTBEAT_INTERVAL_SEC 1
#define PRIMARY_DEATH_TIMEOUT_SEC 5
#define RECOVERY_TIMEOUT_SEC 3
#define RECOVERY_ATTEMPT_LIMIT 10
#define STATE_TRANSFER_TIMEOUT_SEC 2
#define VIEW_CHANGE_TIMEOUT_SEC 20
#define REPLICATION_FACTOR 2
#define CHUNK_SIZE 32
#define MAX_TRANSFERS (META_CHUNKS_MAX * REPLICATION_FACTOR)
#define PARALLEL_TRANSFER_MAX 5

#endif // CONFIG_INCLUDED