#ifndef CONFIG_INCLUDED
#define CONFIG_INCLUDED

#define MAX_SERVER_ADDRS 4
#define MAX_CHUNK_SERVERS 128
#define MAX_OPERATIONS 128
#define MAX_REQUESTS_PER_QUEUE 128

#define REPLICATION_FACTOR 3


#define SYNC_INTERVAL 10
#define RESPONSE_TIME_LIMIT 90

#endif // CONFIG_INCLUDED
